### ISSUE TITLE
wine-proton cannot get a driver, while wine-vanilla can do so just fine

### ISSUE THREAD

**Issue by 0x000C0A71** [ValveSoftware/wine#226] opened 2024-03-26 23:44 UTC
I'm trying to get steam games working and I have trouble with wine proton.

Infos about my system:
- OS: Gentoo
- GPU: RX 5700 XT
- Session: Hyprland/wlroots
- Window server: wayland with xwayland for x11 support

I've installed both wine-vanilla and wine-proton. I tested both by opening a regedit window (`wine-vanilla regedit` & `wine-proton regedit`) and observed the following:
- wine-vanilla launches no problem with both the wayland & the x11 backend for wine.
- wine-proton cannot find a driver on either backend:
```
marc@MarcDesktop ~ $ wine-proton regedit
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
002c:err:winediag:getaddrinfo Failed to resolve your host name IP
007c:fixme:wineusb:add_usb_device Interface 1 has 6 alternate settings; using the first one.
007c:fixme:wineusb:add_usb_device Interface 1 has 2 alternate settings; using the first one.
007c:fixme:wineusb:add_usb_device Interface 2 has 2 alternate settings; using the first one.
007c:fixme:wineusb:add_usb_device Interface 1 has 15 alternate settings; using the first one.
007c:fixme:wineusb:add_usb_device Interface 3 has 5 alternate settings; using the first one.
007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
0074:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
0074:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0074:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0074:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
00d8:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
00d8:err:winediag:nodrv_CreateWindow L"The explorer process failed to start."
00d8:err:systray:initialize_systray Could not create tray window
0114:fixme:oleacc:find_class_data unhandled window class: L"#32769"
0114:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
0114:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
0114:fixme:uiautomation:msaa_fragment_get_FragmentRoot 000000000033FF78, 000000000021FAC0: stub!
00d0:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
00d0:err:winediag:nodrv_CreateWindow L"Make sure that your X server is running and that $DISPLAY is set correctly."
0114:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0114:err:winediag:nodrv_CreateWindow L"Make sure that your X server is running and
 that $DISPLAY is set correctly."
0114:err:tabtip:wWinMain Failed to create hwnd!
012c:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
012c:err:winediag:nodrv_CreateWindow L"Make sure that your X server is running and that $DISPLAY is set correctly."
0140:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0140:err:winediag:nodrv_CreateWindow L"Make sure that your X server is running and that $DISPLAY is set correctly."
wine: configuration in L"/home/marc/.wine" has been updated.
00d8:err:seh:call_stack_handlers invalid frame 00007FFF146D4048 (0000000000022000-0000000000220000)
00d8:err:seh:NtRaiseException Exception frame is not in stack limits => unable to dispatch exception.
016c:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
016c:err:winediag:nodrv_CreateWindow L"The explorer process failed to start."
016c:err:systray:initialize_systray Could not create tray window
0180:fixme:oleacc:find_class_data unhandled window class: L"#32769"
0180:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
0180:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
0180:fixme:uiautomation:msaa_fragment_get_FragmentRoot 000000000033FD78, 000000000021FAC0: stub!
0180:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0180:err:winediag:nodrv_CreateWindow L"Make sure that your X server is running and that $DISPLAY is set correctly."
0180:err:tabtip:wWinMain Failed to create hwnd!
0164:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0164:err:winediag:nodrv_CreateWindow L"Make sure that your X server is running and that $DISPLAY is set correctly."
016c:err:seh:call_stack_handlers invalid frame 00007FFDD5B39D98 (0000000000022000-0000000000220000)
016c:err:seh:NtRaiseException Exception frame is not in stack limits => unable to dispatch exception. 
```

AFAIK the following lines are a problem:
```
err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
err:winediag:nodrv_CreateWindow L"Make sure that your X server is running and that $DISPLAY is set correctly."
```

My `DISPLAY` variable:
```
marc@MarcDesktop ~ $ echo $DISPLAY
:0
```

I have not the slightest idea what the problem might be, but considering wine-vanilla does not suffer from this, this seems to be an issue with this fork specifically.

**Comment by kisak-valve** [comment] 2024-03-27 02:28
Hello @XerneraC, Proton is primarily intended to be used as part of Steam for Linux. Third party packaging that separates the downstream fork of wine used in Proton from the rest of the project is not supportable.

If you can reproduce this issue with Proton from Steam or a full build of Proton, then there would be something for a Proton dev to ponder.

Closing as not supportable.

**Closed as not planned by kisak-valve** 2024-03-27 02:28 UTC
