### ISSUE TITLE
Proton Experimental Bleeding Edge SDL input issues with non-Steam games (not Steam Input related)

### ISSUE THREAD

**Issue by sjp761** [ValveSoftware/wine#244] opened 2024-07-05 17:46 UTC
With the newest bleeding edge of proton experimental, sdl based input (disabling hidraw) does not work anymore so an xbox controller is not emulated

Reg file used to disable

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\winebus]
"DisableHidraw"=dword:00000001

```

Issue is probably the winebus commits on July 3rd
https://github.com/ValveSoftware/wine/commits/bleeding-edge/

**Comment by kisak-valve** [comment] 2024-07-05 17:51
Hello @sjp761, there's no point in fragmenting the discussion of this issue across multiple issue trackers.

Closing as a duplicate of https://github.com/ValveSoftware/Proton/issues/7874.

**Closed as not planned by kisak-valve** 2024-07-05 17:51 UTC
